---
services:
  db:
    image: gopi0810/mypythonapp1:dbimage
    ports:
      - "3306:3306"
    networks:
      - gopinetwork
    deploy:
      replicas: 2

  auth_service:
    image: gopi0810/mypythonapp1:authimage
    ports:
      - "5001:5001"
    networks:
      - gopinetwork
    deploy:
      replicas: 2

  book_service:
    image: gopi0810/mypythonapp1:bookimage
    ports:
      - "5002:5002"
    networks:
      - gopinetwork
    deploy:
      replicas: 2

  borrow_service:
    image: gopi0810/mypythonapp1:borrowimage
    ports:
      - "5003:5003"
    deploy:
      replicas: 2
    networks:
      - gopinetwork
  frontend_service:
    image: gopi0810/mypythonapp1:frontendimage
      - "5000:5000"
    networks:
      - gopinetwork
    deploy:
      replicas: 2

networks:
  gopinetwork:
    driver: overlay
